EPMDJ-7969: Add dockerfile and nginx.config
Drill4J/admin-ui-root-config pull request #10
Opened 2021-07-08 07:18 UTC by IliaSolovev

2021-07-08 07:22 UTC, IliaSolovev commented on docker-compose.services.yml
> +    image: drill4j/admin-ui
This image does not exist now, because i not sure that it will have so name

2021-07-08 07:23 UTC, IliaSolovev commented on docker-compose.services.yml
> +    image: drill4j/admin-ui
What your suggestion?

2021-07-08 07:55 UTC, RomanDavlyatshin requested changes

2021-07-08 07:55 UTC, RomanDavlyatshin commented on .dockerignore
> +**/yarn-debug.log*
yarn is not utilized in this project. I suggest removing that.

2021-07-08 07:55 UTC, RomanDavlyatshin commented on Dockerfile
> +RUN mv ui/dist dist/ui
I don't see a point in adding `ui` folder here

2021-07-08 07:55 UTC, RomanDavlyatshin commented on docker-compose.services.yml
> +    image: drill4j/admin-ui
1. We can publish any image at any moment and just delete it later
2. `admin-ui-container` ?

2021-07-08 07:55 UTC, RomanDavlyatshin commented on src/index.ejs
> +        "@drill4j/admin-ui": "/ui/Drill4J-admin-ui.js",
I suggest removing `/ui/` prefix

2021-07-08 07:55 UTC, RomanDavlyatshin commented on src/index.ejs
> +        "@drill4j/admin-ui-container": "//localhost:9000/Drill4J-admin-ui-container.js",
These magic port numbers trouble me, we should discuss that

2021-07-08 07:55 UTC, RomanDavlyatshin commented on ui/src/index.css
> +/*! tailwindcss v2.2.4 | MIT License | https://tailwindcss.com */
Why are we adding the generated tailwind css again? 😢 
It is created at build-time, I don't see a reason to commit it.

2021-07-12 09:00 UTC, IliaSolovev commented on Dockerfile
> +RUN mv ui/dist dist/ui
It will remove in the next pr, when i update building apps

2021-07-12 09:01 UTC, merged