EPMDJ-10176: fix read notifications
Drill4J/admin-ui-root-config pull request #111
Opened 2022-02-27 21:45 UTC by dmitrii-kliushentsev

2022-02-28 06:07 UTC, IliaSolovev requested changes

2022-02-28 06:07 UTC, IliaSolovev commented on src/ui/components/panels/notifications-panel/notifications-panel.tsx
> +export const NotificationsPanel = ({ isOpen, onClosePanel, payload: notifications }: NotificationsPanelProps) => {
If we will receive a new notification it won`t display here

2022-03-10 07:25 UTC, IliaSolovev commented on src/ui/pages/agent/agent-page.tsx
> +  const notifications = useAdminConnection<Notification[]>("/notifications") || [];
move it to t2c because build it is a t2c entity

2022-03-19 21:11 UTC, RomanAchilov requested changes

2022-03-19 21:11 UTC, RomanAchilov commented on src/ui/pages/agent/agent-page.tsx
> +function filterNotificationForVersion(notifications: Notification[], version?: string) {
the fact that this is a filter is clear by the method from the array

2022-03-19 21:11 UTC, RomanAchilov commented on src/ui/pages/agent/agent-page.tsx
> +function filterNotificationForVersion(notifications: Notification[], version?: string) {
mb
```suggestion
function getNotificationsByBuildVersion(notifications: Notification[], version?: string) {
```

2022-03-22 18:12 UTC, RomanAchilov approved these changes

2022-03-23 06:37 UTC, IliaSolovev approved these changes

2022-03-30 07:41 UTC, merged