EPMDJ-10175: Add icons and hints in system settings and integrate content alert
Drill4J/admin-ui-root-config pull request #120
Opened 2022-03-04 11:53 UTC by dmitrii-kliushentsev

2022-03-09 07:25 UTC, IliaSolovev requested changes

2022-03-09 07:25 UTC, IliaSolovev commented on src/ui/components/panels/registration/steps/system-settings-registration-step/system-settings-registration-step.tsx
> +                <div tw="space-y-2 text-[13px] leading-20">
What is `space-y-2` class do here

2022-03-09 07:25 UTC, IliaSolovev commented on src/ui/components/panels/settings/agent-settings/system-settings-form/system-settings-form.tsx
> +                <div tw="space-y-2 text-[13px] leading-20">
What is `space-y-2` class do here

2022-03-09 07:25 UTC, IliaSolovev commented on src/ui/components/panels/settings/agent-settings/system-settings-form/system-settings-form.tsx
> +        optional
move it to start of component because it hard to find this props

2022-03-09 14:47 UTC, dmitrii-kliushentsev commented on src/ui/components/panels/registration/steps/system-settings-registration-step/system-settings-registration-step.tsx
> +                <div tw="space-y-2 text-[13px] leading-20">
need for hint layout 
https://www.figma.com/file/p1pxTlQBZl9X7ZvacssWHW/Drill4J-(Main)?node-id=699%3A17367

2022-03-10 07:21 UTC, IliaSolovev approved these changes

2022-03-10 09:09 UTC, merged