EPMDJ-10179: implement status for packages field in system settings form
Drill4J/admin-ui-root-config pull request #121
Opened 2022-03-04 11:55 UTC by dmitrii-kliushentsev

2022-03-09 07:08 UTC, IliaSolovev requested changes

2022-03-09 07:08 UTC, IliaSolovev commented on src/ui/components/panels/settings/agent-settings/system-settings-form/system-settings-form.tsx
> +                ...status,
Why you use spread operator here when status it is a object with one property that you update here

2022-03-09 07:08 UTC, IliaSolovev commented on src/ui/components/panels/settings/agent-settings/system-settings-form/system-settings-form.tsx
> +  const { status, setStatus } = useFormikContext();
It looks like a hack. but i don`t know how do it another way. So leave it as it

2022-03-09 13:20 UTC, dmitrii-kliushentsev commented on src/ui/components/panels/settings/agent-settings/system-settings-form/system-settings-form.tsx
> +                ...status,
it is necessary for the possibility of further expansion of the status

2022-03-09 13:21 UTC, IliaSolovev commented on src/ui/components/panels/settings/agent-settings/system-settings-form/system-settings-form.tsx
> +                ...status,
YAGNI

2022-03-09 13:30 UTC, IliaSolovev commented on src/ui/components/panels/settings/agent-settings/system-settings-form/system-settings-form.tsx
> +  const { status, setStatus } = useFormikContext();
add types for status

2022-03-11 06:11 UTC, IliaSolovev approved these changes

2022-03-14 01:53 UTC, merged